# docker-compose.yml
version: "3"

services:
  back:
    build: ./backfiles
    volumes:
      - .:/usr/app
    ports:
      - "3001:3001"

  # frontend:
  #   build: ./front
  #   depends_on:
  #     - backend
  #   links:
  #     - backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/app
